name: fission_env
channels:
  - conda-forge
dependencies:
  - python
  - matplotlib
  - bokeh
  - ipywidgets
  - notebook
  - numpy
  - openpyxl
  - pandas
  - pip
  - scipy
  - pip
  - xlrd
  - cryptography
  - simplegeneric
  - cython
